Feature: DB 설계 및 연동
najasin/na-jasin-be pull request #10
Opened 2023-08-11 01:36 UTC by adoo24

> ### PR Introduce
db
> ### Description
각 도메인의 엔티티를 구성하고 DB랑 연동한다.

> ### etc
[ERD 사진]
https://drive.google.com/file/d/1X3O2bCknBGNCR6UFVKc_x1RVNnYsDxJ4/view?usp=sharing

Comment 테이블은 타인이 나에 대한 질문에 대한 답을 담아둡니다.

그리고 question의 questionType이라는 컬럼은 FOR_USER, FOR_OTHERS로 나뉘는데
이는 질문 자체가 애초에 내가 답하는 질문과 타인이 답하는 질문 두개의 타입으로 나뉠 것이라는 요구사항을 반영하기 위해 만들어졌습니다.

2023-08-11 01:46 UTC, adoo24 commented
application.yml 설정때문에 톰캣 에러가 떠서 수정 후 다시 올리겠습니다

2023-08-11 02:04 UTC, adoo24 commented
yml 파일이 달라서 생긴 문제였네요 ㅎㅎ; 다시 열겠습니다

2023-08-12 04:43 UTC, lcomment requested changes
고생하셨습니다.
공통적인 코멘트 몇개 남겨두겠습니다.

1. 복합키 관련
: 복합키 클래스가 모두 `~~~ID`로 네이밍 돼있는데, 카멜케이스로 수정하는 편이 좋아보입니다. (`~~Id`)

2. 엔티티 기본생성자 관련
: 무분별한 객체 생성을 막기 위해 접근제한자를 넣어주세요! 
```java
@NoArgsConstructor(access = AccessLevel.PROTECTED)
```

2023-08-12 04:43 UTC, lcomment commented on src/main/java/com/najasin/domain/userType/entity/UserType.java
> +    private String name;
user type은 두가지 명사이므로 name에서 `user_type_id`, `user_type_name`으로 두는 것이 좋아보이네요!

2023-08-14 04:36 UTC, adoo24 commented
@lcomment 해당 사항들 수정 완료하였습니다! 리뷰 감사합니다

2023-08-14 04:54 UTC, lcomment approved these changes

2023-08-14 04:54 UTC, merged

2023-08-14 04:54 UTC, lcomment commented
고생하셨어요!